services:
#    perso_platform.example:
#        class: Perso\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Perso_platform.antispam:
      class: Perso\PlatformBundle\Antispam\PersoAntispam
      arguments:
            - "@mailer"
            - %locale%
            - 50

    Perso_platform.email.application_mailer:
      class: Perso\PlatformBundle\Email\ApplicationMailer
      arguments:
            - "@mailer"

    Perso_platform.doctrine_listener.application_creation:
      class: Perso\PlatformBundle\DoctrineListener\ApplicationCreationListener
      arguments:
            - "@Perso_platform.email.application_mailer"
      tags:
            - { name : doctrine.event_listener, event: postPersist }