services:
#    perso_platform.example:
#        class: Perso\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Perso_platform.antispam:
      class: Perso\PlatformBundle\Antispam\PersoAntispam
      arguments:
            - "@mailer"
            - %locale%
            - 50